<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_arus_kas extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_metode_pembayaran by pk
     */
    // function get_m_metode_pembayaran($pk)
    // {
    //     return $this->db->get_where('m_metode_pembayaran',array('pk'=>$pk))->row_array();
    // }
    
    /*
     * Get all m_metode_pembayaran
     */
    function get_all_m_arus_kas()
    {   
        return $this->db->query("SELECT head,a.kode,nama,SUM(saldo) AS saldo,tahunbulan,proyekfk,kontrakfk from acc_biaya a join acc_kiraan b on a.kode = b.kode GROUP BY head,kode,tahunbulan ORDER BY tahunbulan, kode")->result_array();

    }
	
	function get_x_m_arus_kas($params)
    {   
        return $this->db->query("SELECT head,a.kode,nama,SUM(saldo) AS saldo,tahunbulan,proyekfk,kontrakfk from acc_biaya a join acc_kiraan b on a.kode = b.kode WHERE tahunbulan = '".$params['tahun'].$params['bulan']." GROUP BY head,kode,tahunbulan ORDER BY tahunbulan, kode")->result_array();

    }

}
