<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_buku_besar extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    function get_all_m_buku_besar()
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,LEFT(kode,1) AS head,debit,kredit FROM `t_gjurnal` t 
                                  join t_gjurnal_vc v on 
                                  t.noindex = v.noindex_jurnal")->result_array();


    }

    function get_all_m_buku_besar_sekarang($tanggal_awal, $tanggal_akhir)
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,LEFT(kode,1) AS head,debit,kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE tanggal BETWEEN '$tanggal_awal' and '$tanggal_akhir'")->result_array();

    }

    function get_all_m_buku_besar_kode()
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,debit,kredit FROM `t_gjurnal` t 
                                  join t_gjurnal_vc v on 
                                  t.noindex = v.noindex_jurnal GROUP BY kode")->result_array();


    }

    function pencarian_kode($kode)
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,LEFT(kode,1) AS head,debit,kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE kode='$kode'")->result_array();

    }

    function pencarian_tanggal($tanggal_awal, $tanggal_akhir)
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,LEFT(kode,1) AS head,debit,kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE tanggal BETWEEN '$tanggal_awal' and '$tanggal_akhir'")->result_array();

    }

    function pencarian_tanggal_kode($tanggal_awal, $tanggal_akhir,$kode)
    {   
        return $this->db->query("SELECT tanggal,nojurnal,t.keterangan,kode,LEFT(kode,1) AS head,debit,kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE (kode='$kode') AND (tanggal BETWEEN '$tanggal_awal' and '$tanggal_akhir')
                                ")->result_array();

    }


    function saldo_akhir_kode($kode, $tanggal_awal, $tanggal_akhir)
    {   
        return $this->db->query("SELECT LEFT(kode,1) AS head, SUM(debit) AS debit, SUM(kredit) AS kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE (kode='$kode') AND (tanggal BETWEEN '$tanggal_awal' and '$tanggal_akhir')
                                ")->result_array();

    }

    function saldo_awal_kode($kode, $tanggal_awal)
    {   
        return $this->db->query("SELECT LEFT(kode,1) AS head, SUM(debit) AS debit, SUM(kredit) AS kredit FROM `t_gjurnal` t 
                                JOIN t_gjurnal_vc v ON 
                                t.noindex = v.noindex_jurnal
                                WHERE (kode='$kode') AND (tanggal < '$tanggal_awal')")->result_array();

    }   

}
