<?php

/* 

 * Generated by CRUDigniter v3.0 Beta 

 * www.crudigniter.com

 */

 

class M_dashboard extends CI_Model

{

    function __construct()

    {

        parent::__construct();

    }

    

        public function cek_login($username){

        return $this->db->get_where('admin',array('username'=>$username))->row_array();

    }

}

