<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_neraca extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
	/* function get_x_m_neraca($params)
    {   
        return $this->db->query("SELECT * from ((SELECT head,kode,SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_aktifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']."
     GROUP BY head,kode) UNION 
    (SELECT head,kode,SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_pasifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']." AND kode<>32020 
     GROUP BY head,kode) 
     UNION (SELECT 2,32020,SUM(a.saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM ((SELECT head,kode,SUM(saldo) AS saldo FROM acc_pendapatan 
     WHERE tahunbulan > 201612 AND tahunbulan<=".$params['tahun'].$params['bulan']."
     GROUP BY head,kode) 
     UNION (SELECT head,kode,-SUM(saldo) AS saldo FROM acc_biaya 
     WHERE tahunbulan > 201612 AND tahunbulan<=".$params['tahun'].$params['bulan']."
    GROUP BY head,kode))a)) n join acc_kiraan m on n.kode = m.kode")->result_array();

    } */
	
	function get_x_m_neraca($params)
    {   
        return $this->db->query("SELECT * from ((SELECT head,kode,SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_aktifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']." GROUP BY head,kode) UNION     (SELECT head,kode,SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_pasifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']." AND kode<>32020 GROUP BY head,kode) UNION (SELECT 2,32020,SUM(a.saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM ((SELECT head,kode,SUM(saldo) AS saldo FROM acc_pendapatan WHERE tahunbulan > ".($params['tahun']-1)."12 AND tahunbulan<=".$params['tahun'].$params['bulan']." GROUP BY head,kode) UNION (SELECT head,kode,-SUM(saldo) AS saldo FROM acc_biaya WHERE tahunbulan > ".($params['tahun']-1)."12 AND tahunbulan<=".$params['tahun'].$params['bulan']." GROUP BY head,kode))a)) n join acc_kiraan m on n.kode = m.kode")->result_array();

    }
	
	function get_harta_m_neraca($params){
		return $this->db->query("SELECT SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_aktifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']."")->result_array();
	}

	function get_modal_m_neraca($params){
		return $this->db->query("SELECT SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM ((SELECT head,kode,SUM(saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM acc_pasifa WHERE tahunbulan<=".$params['tahun'].$params['bulan']." AND kode<>32020 GROUP BY head,kode) UNION (SELECT 2,32020,SUM(a.saldo) AS saldo,'".$params['tahun'].$params['bulan']."' AS tahunbulan FROM ((SELECT head,kode,SUM(saldo) AS saldo FROM acc_pendapatan WHERE tahunbulan > ".($params['tahun']-1)."12 AND tahunbulan<=".$params['tahun'].$params['bulan']." GROUP BY head,kode) UNION (SELECT head,kode,-SUM(saldo) AS saldo FROM acc_biaya WHERE tahunbulan > ".($params['tahun']-1)."12 AND tahunbulan<=".$params['tahun'].$params['bulan']." GROUP BY head,kode))a)) n")->result_array();
	}
}
