<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Arus_kas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_arus_kas');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_metode_pembayaran
     */
    function index()
    {
        $data['m_arus_kas'] = $this->M_arus_kas->get_all_m_arus_kas();

        $data['_view'] = 'arus_kas/index';
        $this->load->view('layout/main', $data);
    }
	
	function search()
    {
        $this->form_validation->set_rules('tahun','Tahun','required');

		$this->form_validation->set_rules('bulan','Bulan','required');
		
		if($this->form_validation->run()){
			$params =array( 
				'tahun' => $this->input->post('tahun'),
				'bulan' => $this->input->post('bulan'),
			);
			$data['m_arus_kas'] = $this->M_arus_kas->get_x_m_arus_kas($params);
			$data['_view'] = 'arus_kas/index';
			$this->load->view('layout/main', $data);
		}
		else{
			$data['m_arus_kas'] = $this->M_arus_kas->get_all_m_arus_kas();
			$data['_view'] = 'arus_kas/index';
			$this->load->view('layout/main', $data);
		}
		
    }
    
}
