<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Buku_besar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_buku_besar');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_buku_besar
     */
    function index()
    {
    
        $tanggal_awal = date('Y-m-01');
        $tanggal_akhir = date('Y-m-t');

        $data['m_buku_besar'] = $this->M_buku_besar->pencarian_tanggal_kode($tanggal_awal, $tanggal_akhir,'11010');
        $data['m_buku_besar_kode'] = $this->M_buku_besar->get_all_m_buku_besar_kode();

        $data['saldo_awal'] = $this->M_buku_besar->saldo_awal_kode('11010', $tanggal_awal);
        $data['saldo_akhir'] = $this->M_buku_besar->saldo_akhir_kode('11010', $tanggal_awal, $tanggal_akhir);


        $data['_view'] = 'buku_besar/index';
        $this->load->view('layout/main', $data);
    }

    function pencarian(){
        
        if(($kode=$this->input->post('date_awal')=='') && ($kode=$this->input->post('date_akhir')=='') && ($kode=$this->input->post('kode')!='')){
            $kode=$this->input->post('kode');
            
            $data['m_buku_besar'] = $this->M_buku_besar->pencarian_kode($kode);
   
        }else if(($kode=$this->input->post('date_awal')!='') && ($kode=$this->input->post('date_akhir')!='') && ($kode=$this->input->post('kode')=='')){
            $tanggal_awal=$this->input->post('date_awal');
            $tanggal_akhir=$this->input->post('date_akhir');

            $tanggal_awal2 = date('Y-m-d', strtotime($tanggal_awal));
            $tanggal_akhir2 = date('Y-m-d', strtotime($tanggal_akhir));
            
            $data['m_buku_besar'] = $this->M_buku_besar->pencarian_tanggal($tanggal_awal2, $tanggal_akhir2);
   
        }else if(($kode=$this->input->post('date_awal')!='') && ($kode=$this->input->post('date_akhir')!='') && ($kode=$this->input->post('kode')!='')){
            $tanggal_awal=$this->input->post('date_awal');
            $tanggal_akhir=$this->input->post('date_akhir');
            $kode=$this->input->post('kode');

            $tanggal_awal2 = date('Y-m-d', strtotime($tanggal_awal));
            $tanggal_akhir2 = date('Y-m-d', strtotime($tanggal_akhir));
            
            $data['m_buku_besar'] = $this->M_buku_besar->pencarian_tanggal_kode($tanggal_awal2, $tanggal_akhir2,$kode);

            $data['saldo_awal'] = $this->M_buku_besar->saldo_awal_kode($kode, $tanggal_awal2);
            $data['saldo_akhir'] = $this->M_buku_besar->saldo_akhir_kode($kode, $tanggal_awal2, $tanggal_akhir2);
   
        }else if(($kode=$this->input->post('date_awal')=='') && ($kode=$this->input->post('date_akhir')=='') && ($kode=$this->input->post('kode')=='')){
            $this->session->set_flashdata('message','Pilih salah satu');
            $data['m_buku_besar'] = $this->M_buku_besar->get_all_m_buku_besar();
        }
        
        $data['m_buku_besar_kode'] = $this->M_buku_besar->get_all_m_buku_besar_kode();
        $data['_view'] = 'buku_besar/index';
        $this->load->view('layout/main', $data);
        
    }

    
}
