<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_dashboard');

    } 

    /*
     * Listing of company
     */
    function index()
    {

        if($this->session->userdata('islogin')) {

            $data['_view'] = 'layout/home';
            $this->load->view('layout/main', $data);

        } else {

            $this->load->view('layout/login');

        }

    }

    /*
     * Adding a new company
     */
function login_proccess()
 {   
 $this->load->library('form_validation');

 $username = $this->input->post('username');
 $password = $this->input->post('password');
  

 $login = $this->M_dashboard->cek_login($username);

 if($this->encrypt->decode($login['password']) == $password) {

  $this->session->set_userdata('username',$username); // set session username
  
  $this->session->set_userdata('islogin', true); 
  
  redirect(site_url('dashboard'));
       
 } else {
  //login gagal
  $this->session->set_flashdata('message','Username atau password salah');
  redirect('dashboard');
 }

}
        
        public function logout(){
            $this->session->sess_destroy();
            redirect('dashboard');
        }
        
    }
