<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Laba_rugi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_laba_rugi');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_metode_pembayaran
     */
    function index()
    {
        $data['m_laba_rugi'] = $this->M_laba_rugi->get_all_m_laba_rugi();

        $data['_view'] = 'laba_rugi/index';
        $this->load->view('layout/main', $data);
    }
    
}
