<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Neraca extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_neraca');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_metode_pembayaran
     */
    function index()
    {
        $params =array( 
				'tahun' => date('Y'),
				'bulan' => date('m'),
			);
		$data['harta'] = $this->M_neraca->get_harta_m_neraca($params);
		$data['modal'] = $this->M_neraca->get_modal_m_neraca($params);
		$data['m_neraca'] = $this->M_neraca->get_x_m_neraca($params);
		$data['bulan'] = $this->bulan_ind(date('n')); 
		$data['tahun'] = date('Y');
        $data['_view'] = 'neraca/index';
        $this->load->view('layout/main', $data);
    }
	
	function search()
    {
        $this->form_validation->set_rules('tahun','Tahun','required');

		$this->form_validation->set_rules('bulan','Bulan','required');
		
		$this->form_validation->run();
			$params =array( 
				'tahun' => $this->input->get('tahun'),
				'bulan' => $this->input->get('bulan'),
			);
			$data['harta'] = $this->M_neraca->get_harta_m_neraca($params);
			$data['modal'] = $this->M_neraca->get_modal_m_neraca($params);
			$data['bulan'] = $this->bulan_ind($this->input->get('bulan')); 
			$data['tahun'] = $this->input->get('tahun');
			$data['m_neraca'] = $this->M_neraca->get_x_m_neraca($params);
			$data['_view'] = 'neraca/index';
			$this->load->view('layout/main', $data);
		
		/* else{
			$data['m_arus_kas'] = $this->M_arus_kas->get_all_m_arus_kas();
			$data['_view'] = 'arus_kas/index';
			$this->load->view('layout/main', $data);
		} */
		
    }
	
	private function bulan_ind($no){
		switch($no){
			case '01':
				$bulan = 'Januari';
				break;
			case '02':
				$bulan = 'Februari';
				break;
			case '03':
				$bulan = 'Maret';
				break;
			case '04':
				$bulan = 'April';
				break;
			case '05':
				$bulan = 'Mei';
				break;
			case '06':
				$bulan = 'Juni';
				break;
			case '07':
				$bulan = 'Juli';
				break;
			case '08':
				$bulan = 'Agustus';
				break;
			case '09':
				$bulan = 'September';
				break;
			case '10':
				$bulan = 'Oktober';
				break;
			case '11':
				$bulan = 'November';
				break;
			case '12':
				$bulan = 'Desember';
				break;
		}
		return $bulan;
	}
    
}
